### ISSUE TITLE
All translations aren't displaying

### ISSUE THREAD

**Issue by fxbenard** [samikeijonen/edd-feedback#3]
The plugin description is (textdomain working!) but nothing in the EDD plugin tab section - just plain english

**Comment by samikeijonen** [comment]
Do you mean `wp-admin/edit.php?post_type=download&page=edd-settings&tab=extensions` admin page? I can see translations in Finnish there.

**Comment by fxbenard** [comment]
I checked in another site and it's working fine... Not a plugin issue. Sorry for the disturb
